version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    assignees:
      - fmasuhr

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - fmasuhr
