language: ruby

cache:
  bundler: true
  directories:
    - $(npm config get prefix)/lib/node_modules # global NPM packages

before_install:
  - pip install awscli --upgrade --user

script: bundle exec jekyll build

deploy:
  - provider: script
    script:
      npm install -g snyk;
      snyk monitor --org=fmasuhr
    on:
      branch: master
  - provider: script
    script: aws s3 sync --acl public-read --delete _site/ s3://$AWS_BUCKET
    skip_cleanup: true
    on:
      branch: master
