language: ruby

cache:
  bundler: true
  pip: true
  directories:
    - $(npm config get prefix)/lib/node_modules # global NPM packages

script: bundle exec jekyll build

deploy:
  - provider: script
    script:
      pip install awscli --upgrade --user;
      aws s3 sync --acl public-read --delete _site/ s3://$AWS_BUCKET
    skip_cleanup: true
    on:
      branch: master
