language: ruby

cache:
  bundler: true
  directories:
    - $(npm config get prefix)/lib/node_modules # global NPM packages

script: bundle exec jekyll build

deploy:
  - provider: script
    script:
      npm install -g snyk;
      snyk monitor --org=fmasuhr
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: bundle exec s3_website push
    skip_cleanup: true
    on:
      branch: master
