language: ruby

cache:
  bundler: true
  directories:
    - $(npm config get prefix)/lib/node_modules # global NPM packages

before_install:
  - npm install -g snyk

script: bundle exec jekyll build

deploy:
  - provider: script
    script: snyk monitor --org=fmasuhr
    on:
      branch: master
  - provider: script
    script: bundle exec s3_website push
    on:
      branch: master
