language: ruby

cache:
  bundler: true
  directories:
    - $(npm config get prefix)/lib/node_modules # global NPM packages

before_script:
  - bundle exec s3_website install # Needs to happen after install and allows caching the JAR for usage in the deploy

script: bundle exec jekyll build

deploy:
  - provider: script
    script:
      npm install -g snyk;
      snyk monitor --org=fmasuhr
    on:
      branch: master
  - provider: script
    script: rvm use $(cat .ruby-version) do bundle exec s3_website push
    skip_cleanup: true
    on:
      branch: master
