# Site settings
brand: fionn.
description: >-
  Fionn Masuhr is an experienced software engineer specialized in AWS and cloud infrastructure.
  He has a comprehensive skill set in DevOps and system architecture which he
  successfully used to build scalable cloud solutions and implementing CI/CD pipelines.
url:   https://www.fionn.io

# Social settings
author:
  name:       Fionn Masuhr
  profession: Software Engineer
github:
  title:    GitHub
  username: fmasuhr
linkedin:
  title:   LinkedIn
  profile: fionn-masuhr-975a84350
stackoverflow:
  id:    5346940
  title: Stack Overflow
xing:
  title:    XING
  username: Fionn_Masuhr

# Build settings
exclude:
  - LICENSE
  - package-lock.json
  - package.json
  - README.md

plugins:
  - jekyll-seo-tag

sass:
  style: compressed
