# Site settings
brand: fionn.
description: >-
  Fionn Masuhr is an experienced DevOps engineer specializing in AWS and cloud computing.
  He has a comprehensive skill set in AWS services and cloud architecture which he
  successfully used to build CI/CD pipelines, and implementing scalable cloud solutions.
url:   https://www.fionn.io

# Social settings
author:
  name:       Fionn Masuhr
  profession: Software Engineer
github:
  title:    GitHub
  username: fmasuhr
stackoverflow:
  id:    5346940
  title: Stack Overflow
xing:
  title:    XING
  username: Fionn_Masuhr

# Build settings
exclude:
  - LICENSE
  - package-lock.json
  - package.json
  - README.md

plugins:
  - jekyll-seo-tag

sass:
  style: compressed
