# Site settings
brand: fionn.
description: >-
  Personal Webpage of Fionn Masuhr, located in Germany.
  Software Engineer for Web development, AWS and Ruby.
  Professionalized in DevOPS and Backend Engineering.
url:   https://www.fionn.io

# Social settings
author:
  name:       Fionn Masuhr
  profession: Software Engineer
github:
  title:    GitHub
  username: fmasuhr
stackoverflow:
  id:    5346940
  title: Stack Overflow
xing:
  title:    XING
  username: Fionn_Masuhr

# Build settings
exclude:
  - LICENSE
  - package-lock.json
  - package.json
  - README.md

plugins:
  - jekyll-seo-tag

sass:
  style: compressed
