# Site settings
description: >-
  Personal Webpage of Fionn Masuhr, located in Brunswick.
  Software Engineer for Web development, AWS and Ruby.
  Professionalized in DevOPS and Backend Engineering.
title: fionn.
url:   https://www.fionn.io

# Social settings
author:
  name:           Fionn Masuhr
  profession:     Software Engineer
github_username:  fmasuhr
stackoverflow_id: 5346940
xing_username:    Fionn_Masuhr

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - s3_website.yml
  - vendor/

plugins:
  - jekyll-seo-tag

sass:
  style: compressed
