name: Auto-merge

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-20.04
    if: ${{ github.actor == 'dependabot[bot]' && github.event.workflow_run.pull_requests[0] }}

    steps:
      - id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.2.0
        with:
          github-token: ${{ github.token }}
      - name: Merge PR
        uses: pascalgn/automerge-action@v0.14.3
        if: ${{ (contains(['bundler', 'npm'], steps.dependabot-metadata.outputs.package-ecosystem) && steps.dependabot-metadata.outputs.dependency-type == 'direct:development' }}
        env:
          MERGE_LABELS: '' # all
          GITHUB_TOKEN: ${{ github.token }}
